version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"
