version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    rebase-strategy: "disabled"
    target-branch: "develop"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"
