name: dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build_dev:
    name: build_dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Build container image
        uses: docker/build-push-action@v2.8.0
        with:
          push: false
          tags: ${{github.repository}}:${{github.sha}}
