name: dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_dev:
    name: build_dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.8.0

      - name: Build container image
        uses: docker/build-push-action@v4.1.1
        with:
          push: false
          tags: ${{github.repository}}:${{github.sha}}
